apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-one
data:
  index.html: |
    <html>
    <body>
    <h1>This is Deployment One</h1>
    </body>
    </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-two
data:
  index.html: |
    <html>
    <body>
    <h1>This is Deployment Two</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      deployment: deployment-one
  template:
    metadata:
      labels:
        app: nginx
        deployment: deployment-one
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-html
        configMap:
          name: deployment-one

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      deployment: deployment-two
  template:
    metadata:
      labels:
        app: nginx
        deployment: deployment-two
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-html
        configMap:
          name: deployment-two

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
