# This YAML file contains Kubernetes deployment and service specifications for three applications: Redis, Apache, and Postgres.

# The first section defines a Deployment for Redis with four replicas, using the Redis image on port 6379.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 4
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

# The second section defines a Deployment for Apache with ten replicas, using the httpd image on port 80.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 10
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80

# The third section defines a Deployment for Postgres with one replica, using the postgres image on port 5432.
# It also sets environment variables for the POSTGRES_USER and POSTGRES_PASSWORD.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password

# The fourth section defines a Service for Redis, exposing it using the ClusterIP type on port 6379.
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP

# The fifth section defines a Service for Apache, exposing it using the LoadBalancer type on port 80.
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
    - name: apache
      port: 80
      targetPort: 80
  type: LoadBalancer

# The sixth section defines a Service for Postgres, exposing it using the ClusterIP type on port 5432.
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
