version: "3"

services:
  redis:
    image: redis
    replicas: 4
    ports:
      - "6379"
  apache:
    image: httpd
    replicas: 10
    ports:
      - "80"
  postgres:
    image: postgres
    replicas: 1
    ports:
      - "5432"
      